# Generated by Django 5.2.6 on 2025-10-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authentication',
            old_name='code_attempts',
            new_name='code_attempt',
        ),
        migrations.AddField(
            model_name='authentication',
            name='password_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
