# Generated by Django 5.2.6 on 2025-10-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_code_attempts_authentication_code_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='blocked_until',
            field=models.DateTimeField(null=True),
        ),
    ]
