# Generated by Django 5.2.6 on 2025-10-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_authentication_blocked_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authentication',
            old_name='user_id',
            new_name='user',
        ),
    ]
