# Generated by Django 5.2.6 on 2025-10-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_user_id_authentication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
