name: Full-Stack CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Vérification du dépôt
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.17'

      - name: Installation des dépendances
        run: npm install
        working-directory: ./frontend

      - name: Lancement des tests
        run: npm test -- --run
        working-directory: ./frontend
        env :
          VITE_API_URL: "http://127.0.0.1:8000/api/"


      - name: Build
        run: npm run build
        working-directory: ./frontend

  backend:
    name: Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: local_admin
          POSTGRES_PASSWORD: local_password
          POSTGRES_DB: 'local_db'
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        
    steps:
      - name: Vérification du dépôt
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Installation des dépendances
        run: |
          python -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r requirements.txt

      - name: Lancement des tests
        run: |
          ./venv/bin/pytest --tb=short -v
        env:
          DJANGO_SETTINGS_MODULE: backend.settings
